# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: csharp
solution: DeviceDetection.UWP.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore DeviceDetection.UWP.sln
